/** Single source of truth for the version shown in the Android APK and the update manifest. */
export const APP_RELEASE = {
  version: "1.1.0",
  androidVersionCode: 2,
  releasedAt: "2026-08-20T20:00:00.000Z",
  channel: "Production",
  apkIntegrity: {
    assetName: "BlackBox-1.1.0.apk",
    algorithm: "SHA-256" as const,
    // Populate only from the actual signed APK generated by the Android publish flow. Never insert a sample checksum.
    sha256: null as string | null,
    // Signing-certificate fingerprint from the generated production release keystore.
    signingCertificateSha256: "004fdfd9025b62df1264d72739db9fc7ce248df9e9a9bc20b18a52990ef3de2a" as string | null,
    // Populate only with the public HTTPS download address for the signed APK that matches the checksum above.
    verifiedDownloadUrl: null as string | null,
  },
  notes: [
    "Added guarded selected-module test runs through the private gateway.",
    "Added in-app system verification for local, GitHub, PDF, and gateway module readiness.",
    "Added module-specific completed-scan result summaries and APK release visibility.",
  ],
} as const;
