import { router } from "expo-router";
import { FlatList, Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useState } from "react";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { EmptyCard, LoadingView, PrimaryButton, QuietButton, SectionLabel, palette } from "@/components/workspace-ui";
import { ScreenContainer } from "@/components/screen-container";
import { TARGET_TYPES, TargetType, formatDate } from "@/lib/workspace-model";
import { useWorkspace } from "@/lib/workspace-context";

export default function WorkspacesScreen() {
  const { ready, workspaces, jobs, createWorkspace } = useWorkspace();
  const [open, setOpen] = useState(false); const [name, setName] = useState(""); const [targetType, setTargetType] = useState<TargetType>("Mobile package");
  if (!ready) return <LoadingView />;
  const save = () => { const workspace = createWorkspace(name, targetType); if (!workspace) return; setName(""); setOpen(false); router.push({ pathname: "/workspace/[id]", params: { id: workspace.id } }); };
  return <ScreenContainer containerClassName="bg-[#101620]" safeAreaClassName="bg-[#101620]"><FlatList data={workspaces} keyExtractor={(item) => item.id} contentContainerStyle={styles.content}
    ListHeaderComponent={<><View style={styles.topRow}><View><Text style={styles.eyebrow}>LOCAL ENGAGEMENTS</Text><Text style={styles.title}>Workspaces</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Create workspace" onPress={() => setOpen(true)} style={({ pressed }) => [styles.addButton, pressed && styles.pressed]}><IconSymbol name="plus" size={22} color={palette.base} /></Pressable></View><SectionLabel>{workspaces.length ? `${workspaces.length} saved workspace${workspaces.length === 1 ? "" : "s"}` : "Start locally"}</SectionLabel></>}
    renderItem={({ item }) => { const jobCount = jobs.filter((job) => job.workspaceId === item.id).length; return <Pressable accessibilityRole="button" accessibilityLabel={`Open workspace ${item.name}`} onPress={() => router.push({ pathname: "/workspace/[id]", params: { id: item.id } })} style={({ pressed }) => [styles.workspaceRow, pressed && styles.pressed]}><View style={styles.workspaceGlyph}><IconSymbol name="folder.fill" size={20} color={palette.teal} /></View><View style={styles.workspaceBody}><Text style={styles.workspaceName} numberOfLines={1}>{item.name}</Text><Text style={styles.workspaceMeta}>{item.targetType} · {jobCount} analysis record{jobCount === 1 ? "" : "s"}</Text><Text style={styles.workspaceDate}>Created {formatDate(item.createdAt)}</Text></View><IconSymbol name="chevron.right" size={18} color={palette.muted} /></Pressable>; }} ItemSeparatorComponent={() => <View style={{ height: 10 }} />}
    ListEmptyComponent={<EmptyCard title="No workspaces yet" detail="Keep each approved engagement organized in its own local workspace before preparing analysis records." action={<PrimaryButton label="Create workspace" onPress={() => setOpen(true)} icon="folder.badge.plus" />} />}
  />
  <Modal transparent visible={open} animationType="slide" onRequestClose={() => setOpen(false)}><View style={styles.modalBackdrop}><View style={styles.sheet}><View style={styles.sheetHandle} /><Text style={styles.sheetTitle}>Create workspace</Text><Text style={styles.sheetDetail}>A workspace is a local organizer for one authorized engagement. It contains no remote credentials.</Text><TextInput value={name} onChangeText={setName} placeholder="Workspace name" placeholderTextColor="#718399" autoFocus returnKeyType="done" onSubmitEditing={save} style={styles.input} /><Text style={styles.inputLabel}>Primary target</Text><View style={styles.choiceWrap}>{TARGET_TYPES.map((item) => <Pressable key={item} accessibilityRole="button" accessibilityState={{ selected: targetType === item }} onPress={() => setTargetType(item)} style={({ pressed }) => [styles.choice, targetType === item && styles.choiceSelected, pressed && styles.pressed]}><Text style={[styles.choiceText, targetType === item && styles.choiceTextSelected]}>{item}</Text></Pressable>)}</View><PrimaryButton label="Save workspace" onPress={save} icon="checkmark.circle.fill" disabled={!name.trim()} /><QuietButton label="Cancel" onPress={() => setOpen(false)} icon="xmark.circle" /></View></View></Modal>
  </ScreenContainer>;
}
const styles = StyleSheet.create({
  content: { paddingHorizontal: 20, paddingTop: 10, paddingBottom: 30, backgroundColor: palette.base, flexGrow: 1 }, topRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 21 }, eyebrow: { color: palette.teal, fontSize: 11, fontWeight: "800", letterSpacing: 1.2 }, title: { color: palette.text, fontSize: 31, lineHeight: 38, fontWeight: "800", letterSpacing: -0.6, marginTop: 3 }, addButton: { width: 44, height: 44, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: palette.teal }, pressed: { opacity: 0.72 }, workspaceRow: { flexDirection: "row", alignItems: "center", gap: 12, borderRadius: 19, padding: 15, backgroundColor: palette.surface, borderWidth: 1, borderColor: palette.border }, workspaceGlyph: { width: 42, height: 42, borderRadius: 14, backgroundColor: palette.tealMuted, alignItems: "center", justifyContent: "center" }, workspaceBody: { flex: 1, gap: 3 }, workspaceName: { color: palette.text, fontSize: 16, fontWeight: "800" }, workspaceMeta: { color: palette.muted, fontSize: 13 }, workspaceDate: { color: "#708093", fontSize: 12, marginTop: 1 },
  modalBackdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(2, 7, 12, 0.74)" }, sheet: { backgroundColor: palette.surfaceStrong, borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 22, paddingBottom: 34, gap: 16 }, sheetHandle: { height: 4, width: 42, borderRadius: 2, backgroundColor: "#607083", alignSelf: "center", marginTop: -8 }, sheetTitle: { color: palette.text, fontSize: 21, fontWeight: "800" }, sheetDetail: { color: palette.muted, fontSize: 14, lineHeight: 20 }, inputLabel: { color: palette.muted, fontSize: 12, fontWeight: "800", letterSpacing: 0.7, textTransform: "uppercase", marginTop: 3 }, input: { color: palette.text, fontSize: 16, backgroundColor: palette.base, borderColor: palette.border, borderWidth: 1, borderRadius: 15, paddingHorizontal: 15, minHeight: 52 }, choiceWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, choice: { paddingHorizontal: 11, paddingVertical: 9, borderRadius: 11, backgroundColor: palette.base, borderWidth: 1, borderColor: palette.border }, choiceSelected: { backgroundColor: palette.tealMuted, borderColor: palette.teal }, choiceText: { color: palette.muted, fontSize: 13, fontWeight: "700" }, choiceTextSelected: { color: palette.teal },
});
